### ISSUE TITLE
Mare builds with Crystal 1.0.0

### ISSUE THREAD

**Issue by mneumann** [jemc/mare#86]
Would be great to be able to compile Mare with Crystal 1.0.0.

**Comment by jemc** [comment]
Looks like you may have already started on this (given your changes in the crystal-lsp repo, so I'm provisionally assigning you to this ticket). Let me know if you want to be unassigned.

**Comment by mneumann** [comment]
@jemc I thought this would be simple, but I am running into hundreds of type errors :(

I could fix some of them, but this looks more like a regression in Crystal 1.0.0.

For instance I had to add these type annotations:

```diff
--- a/src/mare/compiler/interpreter/default.cr
+++ b/src/mare/compiler/interpreter/default.cr
@@ -12,12 +12,12 @@ class Mare::Compiler::Interpreter::Default < Mare::Compiler::Interpreter
       "kind" => "keyword",
       "name" => "keyword",
       "value" => "import",
-    },
+    } of String => String | Bool,
     {
       "kind" => "term",
       "name" => "path",
       "type" => "string",
-    },
+    } of String => String | Bool,
```

Otherwise, Crystal thinks the `Mare::Witness` takes an `Array(Hash(String, String) | Hash(String, String | Bool))`, where
it really should be `Array(Hash(String, String | Bool))`.

If you have crystal 1.0.0 installed, you can see yourself. Let me know if you have any idea how to fix that.

This is the updated shards.yml:

```diff
$ git diff shard.yml 
diff --git a/shard.yml b/shard.yml
index e99cf24..1bc7f62 100644
--- a/shard.yml
+++ b/shard.yml
@@ -12,11 +12,12 @@ dependencies:
   pegmatite:
     github: jemc/crystal-pegmatite
   lsp:
-    github: jemc/crystal-lsp
+    github: mneumann/crystal-lsp
+    branch: convert-to-json-serialize
   clim:
     github: at-grandpa/clim
     version: 0.13.0
 
-crystal: 0.26.1
+crystal: 1.0.0
```

And I am running `crystal build main.cr`.


For WIP, see my commit on this branch: https://github.com/mneumann/mare/tree/works-with-crystal-1.

Crystal's error reporting is all but optimal for these kind of errors :/.

**Comment by jemc** [comment]
You actually already finished most of the heavy lifting on your branch!

There were only a few other source code changes I had to make: https://github.com/jemc/mare/pull/87/commits/5fd86e6293780f038b3b127f04dfab8d2159acf5

And apart from that I committed the content of `shards install` because I like to keep all that in the `git` tree and avoid forcing the compiler devs to have Crystal on their system to run `shards install` (no Crystal is required on the host system because we run all standard development workflow stuff within docker.

And lastly I updated the Dockerfile to use latest alpine, which has Crystal 1.0.0 on it.

Thanks for all the help! Let me know if there are other tickets you want to work on here, or other tickets you'd like to create.

**Comment by mneumann** [comment]
@jemc thanks for finishing that work!

I can now compile Mare on FreeBSD with Crystal 1.0. Running compiled Mare programs still crash, probably due to issues with libponyrt. I'd love to be able to try out Mare without having to resort to Docker (not available on FreeBSD).

**Comment by jemc** [comment]
Thanks, I wasn't aware of Docker not being available on FreeBSD.

It's definitely a goal to get Mare more easily distributable to various platforms. At the start I saw Docker as an easy temporary shortcut, since it's available on many platforms.

I'll open a new ticket to work on getting instructions and/or automation up for running the Mare compiler and its compiled programs outside of Docker. Maybe you can assist with the FreeBSD side of things. I'll ping you in that ticket after I create it.
